### PR TITLE
Moar validations

### PR DESCRIPTION
**Pull request by jennyd**
Add some more validations for cases which have caught us out in the past:

- site abbrs match their filenames
- YAML files are only in the expected directories, and not elsewhere in the repo
- all required fields are present in each site file

Also:

- add a `validate:all` rake task to run all the checks easily
- rename a directory which was omitted from https://github.com/alphagov/transition-config/pull/1017

An incorrect site abbr found by the first validation was fixed in https://github.com/alphagov/transition-config/pull/1151 - that was merged separately because we're switching over to Integration today.

https://trello.com/c/efUNofuq/64-more-validations-for-the-transition-config-ci-build

### CODE REVIEW

**Comment by h-lame** [comment]
This looks really useful.  I wonder if it would be desirable to drop `abbr` from the yaml and always use the filename of the yaml file to avoid this case of errors entirely?  `Site.from_yaml` could then inject `abbr` from the basename of the file used.  Might be a bit too magical though?

**Comment by h-lame** [comment]
Obviously, above, by `abbr` (the method name) I mean `site` (the key in yaml) - this might also help with any confusion about `site` vs. `abbr` (which I just had).

**Comment by sihugh** [comment]
+1 to the aside

**Comment by jennyd** [comment]
Transition uses the `site` from the yaml as the [unique identifier for a site in the import](https://github.com/alphagov/transition/blob/master/lib/transition/import/site_yaml_file.rb#L72) and doesn't look at the filename (the `site` from the yaml is [called `abbr`](https://github.com/alphagov/transition/blob/master/lib/transition/import/site_yaml_file.rb#L18) within Transition), so we would need to change the import to use the filename before changing the structure of the files here. We've considered doing that in the past, but thought there was some value in having the abbreviation inside the file for human readers - perhaps that isn't really the case, though.

**Comment by h-lame** [comment]
Sounds like a change that would have wider-ranging impact than this PR is intended to make.  I'll merge this and we can think about `abbr`/`site` in a different story.

**Pull request merged**
