### PR TITLE
[MHRA] Add ssdocname to significant query strings

### PR DESCRIPTION
**Pull request by jamiecobbett**

### CODE REVIEW

**Comment by adammaddison** [comment]
Jenny was concerned that this might break lots of existing mappings.  We know if that's the case?

**Comment by jennyd** [comment]
From grepping[1] the pre-transition hits files, it looks like adding this and then regenerating mappings from hits will create just over 2000 new mappings. This query param is mostly used in paths like `/home/idcplg/idc_cgi_isapi-CDSPROD2.dll?IdcService=SS_GET_PAGE&ssDocName=CON093783`. As long as MHRA know that they will have to update the mappings created from hits as soon as possible, that sounds like a manageable number of new mappings to me.

I think there won't be many orphaned mappings left after doing this: `sstargetnodeid` appears in hits fairly frequently alongside `ssdocname`, but the former appears in only one mapping at the moment.

[1] `grep 'ssDocName' hits/www.mhra.gov.uk_201* | awk '{ print $5 }' | sort | uniq | wc -l`

**Comment by adammaddison** [comment]
Thanks Jenny. Much appreciated.

**Comment by rgarner** [comment]
I forgot to yell 'p' when this was opened. Ah well, the moment for bad HD jokes has passed.

**Comment by adammaddison** [comment]
Good lord, that's awful!

**Comment by issyl0** [comment]
I was a bit slow with that one. I've just got the joke. :-P

**Pull request merged**
