### PR TITLE
Add a redirect for contractsfinder.businesslink.gov.uk to www.gov.uk/contracts-finder

### PR DESCRIPTION
**Pull request by tombye**
## Please do not merge yet, waiting on confirmation from the ticket originator

The detail of the redirect is described in this story:

https://www.pivotaltracker.com/story/show/98023524

Can either @issyl0 @jennyd or @jamiecobbett please check this prior to merging. Thanks!

### CODE REVIEW

**Comment by tombye** [comment]
Please ignore this. I've just realised the request is to redirect to http://data.gov.uk/data/contracts-archive instead so closing this.

**Comment by jennyd** [comment]
This looks fine as it is, but we're waiting to hear back about more aliases so won't merge yet.

**Comment by tommyp** [comment]
Reply from Tom Scott this morning:
> The service manager confirmed that was the only additional domain domain, for clarity can we redirect both https://online.contractsfinder.businesslink.gov.uk/ and https://www.contractsfinder.businesslink.gov.uk/ to http://data.gov.uk/data/contracts-archive

Is this good to go now?

**Comment by jennyd** [comment]
`online.contractsfinder.businesslink.gov.uk` needs adding as an alias, otherwise I think so.

**Comment by tommyp** [comment]
@jennyd Added an alias for that.

**Comment by jennyd** [comment]
:+1:

**Pull request merged**
