### PR TITLE
Make cdn.hm-treasury an alias of main treasury site

### PR DESCRIPTION
**Pull request by rjc123**

### CODE REVIEW

**Comment by jamiecobbett** [comment]
Should this be merged?

**Comment by rjc123** [comment]
The detail is [here](https://www.pivotaltracker.com/story/show/85004378) - I don't think this should be merged until we remove the CDN treasury site from the database. (An interrelated series of deploy steps need to happen on this one.)

**Comment by mattbostock** [comment]
Should this be closed?

**Comment by jennyd** [comment]
There would be lots of manual cleanup required to merge these sites:

- deleting the site
- deleting or reassiging its mappings
- deleting or merging its hits rows, both in the hits files and the database

The separate `cdn.hm-treasury.gov.uk` site is getting very little traffic (~200 hits a day) and no errors are showing up in Transition for it. I think this change isn't worth the effort it would require to clean up around it, so let's not do it now.

**Pull request closed without merging**
